apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pulsar-helm-operator
  template:
    metadata:
      labels:
        name: pulsar-helm-operator
    spec:
      serviceAccountName: pulsar-helm-operator
      containers:
        - name: pulsar-helm-operator
          image: streamnative/pulsar-helm-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pulsar-helm-operator"
