# Copyright (c) 2020 StreamNative, Inc.. All Rights Reserved.
---
{{- if and .Values.components.pulsar .Values.pulsar.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.pulsar.serviceAccount.name }}'
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    components: {{ .Values.pulsar.component }}
{{- end }}
{{- if and .Values.components.pulsar .Values.pulsar.rbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.pulsar.rbac.name }}'
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    components: {{ .Values.pulsar.component }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - compute.functionmesh.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pulsar.streamnative.io
    resources:
      - pulsarbrokers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pulsar.streamnative.io
    resources:
      - pulsarbrokers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - pulsar.streamnative.io
    resources:
      - pulsarproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pulsar.streamnative.io
    resources:
      - pulsarproxies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.pulsar.rbac.name }}'
subjects:
- kind: ServiceAccount
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.pulsar.serviceAccount.name }}'
  namespace: {{ template "pulsar.namespace" . }}
roleRef:
  kind: ClusterRole
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.pulsar.rbac.name }}'
  apiGroup: rbac.authorization.k8s.io
{{- end }}
