# Copyright (c) 2020 StreamNative, Inc.. All Rights Reserved.
---
{{- if and .Values.components.bookkeeper .Values.bookkeeper.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.serviceAccount.name }}'
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    components: {{ .Values.bookkeeper.component }}
{{- end }}
{{- if and .Values.components.bookkeeper .Values.bookkeeper.rbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.rbac.name }}'
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    components: {{ .Values.bookkeeper.component }}
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bookkeeper.streamnative.io
    resources:
      - bookkeeperclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bookkeeper.streamnative.io
    resources:
      - bookkeeperclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.rbac.name }}'
subjects:
- kind: ServiceAccount
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.serviceAccount.name }}'
  namespace: {{ template "pulsar.namespace" . }}
roleRef:
  kind: ClusterRole
  name: '{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.rbac.name }}'
  apiGroup: rbac.authorization.k8s.io
{{- end }}
