apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pulsarclusters.io.streamnative.helm
spec:
  group: io.streamnative.helm
  names:
    kind: PulsarCluster
    listKind: PulsarClusterList
    plural: pulsarclusters
    singular: pulsarcluster
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
