{{- if .Values.monitoring.grafana }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.grafana.component }}-secret"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.grafana.component }}
    cluster: {{ template "pulsar.fullname" . }}
type: Opaque
stringData:
  {{- if .Values.grafana.admin}}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.grafana.admin.password }}
  GRAFANA_ADMIN_USER: {{ .Values.grafana.admin.user }}
  {{- end }}
{{- end }}