{{- if .Values.monitoring.node_exporter }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.node_exporter.component }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ template "pulsar.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.node_exporter.component }}
    cluster: {{ template "pulsar.fullname" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app: {{ template "pulsar.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.node_exporter.component }}
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: {{ template "pulsar.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.node_exporter.component }}
        cluster: {{ template "pulsar.fullname" . }}
      annotations:
{{ toYaml .Values.node_exporter.annotations | indent 8 }}
    spec:
    {{- if .Values.node_exporter.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.node_exporter.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.node_exporter.tolerations }}
      tolerations:
{{ toYaml .Values.node_exporter.tolerations | indent 8 }}
    {{- end }}
      containers:
        - name: prometheus-node-exporter
          image: "prom/node-exporter:v0.16.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          ports:
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
          {{- if .Values.node_exporter.resources }}
          resources:
{{ toYaml .Values.node_exporter.resources | indent 10 }}
          {{- end }}
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
{{- end }}